[package]
authors = ["Paxon Qiao <qiaopengjun0@gmail.com>"]
description = """

"""
documentation = "https://docs.rs/"
edition = "2024"
license = "MIT"
name = "chat-server"
readme = "README.md"
repository = "https://github.com//ferris-chat"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
argon2 = { version = "0.5.3", features = ["std"] }
axum = { workspace = true }
chrono = { version = "0.4.42", features = ["serde"] }
serde = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
sqlx-db-tester = "0.7.1"
